### ISSUE TITLE
Missing SNI Support

### ISSUE THREAD

**Issue by ramauers** [GsDevKit/zodiac#13]
Playing around on Ubuntu 22.04 and GemStone 3.7.0 I tried the following:

GsSecureSocket useCACertificateFileForClients:  '/etc/ssl/certs/ca-certificates.crt'.
ZnEasy get: 'https://google.com'

...resulting in a certificate validation exception. A ...

GsSecureSocket fetchLastCertificateVerificationErrorForClient

... says:

'Certificate verification error: kind: CLIENT code=18 depth=0 issuer=/OU=No SNI provided; please fix your client./CN=invalid2.invalid subject=/OU=No SNI provided; please fix your client./CN=invalid2.invalid errorMsg=self-signed certificate'

It looks like zodiac is missing SNI support although GsSecureSocket would support it.
According to https://github.com/GsDevKit/zodiac/issues/7 it probably already worked in the past on earlier versions. (Unless the need for SNI on google is younger than 2016.)

**Comment by ramauers** [comment]
I could solve my issue by modifying the below method:

```smalltalk
ZnNetworkingUtils>>socketStreamToUrlDirectly: url
	| stream address |
	address := SpIPAddress ipAddressForHostName: url host timeout: self timeout. 
	stream := (self streamClassForScheme: url scheme) 
		openConnectionToHost: address
		port: url portOrDefault
		timeout: self timeout.  
	self setSocketStreamParameters: stream.  
	(#(https wss) includes: url scheme)
		ifTrue:
			[ "ramauers: Attempt to fix https://github.com/GsDevKit/zodiac/issues/13"
			stream socket setServerNameIndication: url host.
			stream connect ].  
	^ stream
```

Not sure, if that is an appropriate fix.
* Surprised, that fix affects method from package Zinc-HTTP, not Zodiac-Core
* Think so, but did not investigate, if socket is always an instance of GsSecureSocket and understands setServerNameIndication:

**Comment by kurtkilpela** [comment]
This has been resolved by the following PRs:

https://github.com/GsDevKit/zodiac/pull/14
https://github.com/GsDevKit/zinc/pull/108
