### ISSUE TITLE
 ZnClient new get: 'https://www.google.com'. works intermittently..

### ISSUE THREAD

**Issue by pdebruic** [GsDevKit/zodiac#7]
Sorry I don't have a better way to characterize this.  

I ran it with

eval ` ZnClient new get: 'https://www.google.com'.`

Here is the stack:

UserDefinedError: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1258:

--------------------
1. UserDefinedError(AbstractException)>>_signalWith: @6 line 25
2. UserDefinedError(AbstractException)>>signal @2 line 47
3. ZdcGemStoneSSLSession(Object)>>error: @6 line 7
4. [] in ZdcGemStoneSSLSession>>connect:from:to:into: @4 line 14
5. ZdcGemStoneSSLSession(ExecBlock)>>ensure: @2 line 12
6. ZdcGemStoneSSLSession>>connect:from:to:into: @12 line 16
7. ZdcSecureSocketStream>>connect @6 line 8
8. ZnNetworkingUtils>>socketStreamToUrlDirectly: @17 line 9
9. ZnNetworkingUtils>>socketStreamToUrl: @9 line 5
10. ZnNetworkingUtils class>>socketStreamToUrl: @3 line 3
11. ZnClient>>getConnectionAndExecute @13 line 9
12. ZnClient>>executeWithRedirectsRemaining: @2 line 2
13. [] in ZnClient>>executeWithRetriesRemaining: @4 line 2
14. ZnClient(ExecBlock)>>on:do: @3 line 44
15. ZnClient>>executeWithRetriesRemaining: @8 line 3
16. [] in ZnClient>>executeWithTimeout @4 line 3
17. ZnClient(ExecBlock)>>on:do: @3 line 44
18. [] in ZnClient>>executeWithTimeout @4 line 4
19. [] in ExecBlock0(ZnClient)>>withTimeoutDo: @3 line 6
20. [] in ZnConnectionTimeout class(DynamicVariable class)>>value:during: @4 line 9
21. ZnConnectionTimeout class(ExecBlock)>>ensure: @2 line 12
22. ZnConnectionTimeout class(DynamicVariable class)>>value:during: @7 line 10
23. ZnClient>>withTimeoutDo: @6 line 5
24. ZnClient>>executeWithTimeout @3 line 2
25. [] in ZnClient>>execute @3 line 9
26. [] in ExecBlock0(ZnClient)>>withProgressDo: @3 line 6
27. [] in ZnSignalProgress class(DynamicVariable class)>>value:during: @4 line 9
28. ZnSignalProgress class(ExecBlock)>>ensure: @2 line 12
29. ZnSignalProgress class(DynamicVariable class)>>value:during: @7 line 10
30. ZnClient>>withProgressDo: @6 line 5
31. ZnClient>>execute @6 line 8
32. ZnClient>>get @3 line 6
33. ZnClient>>get: @3 line 6
34. Executed Code
35. GsNMethod>>_executeInContext: @1 line 1
36. String(CharacterCollection)>>evaluateIn:symbolList:literalVars: @5 line 13
37. [] in TDShellTool>>eval @7 line 13
38. OrderedCollection(Collection)>>do: @6 line 10
39. TDShellTool>>eval @4 line 9
40. TDShellTool(Object)>>perform: @1 line 1
41. TDShellTool class(TDAbstractDevTool class)>>performCommand:withSelector:objIn:commandOptions:todeCommand: @15 line 10
42. TDShellTool class(TDAbstractDevTool class)>>performCommand:objIn:commandOptions:todeCommand: @2 line 3
43. [] in TDShellTool class>>eval @3 line 5
44. TDShellTool class(ExecBlock)>>cull:cull:cull:cull: @7 line 4
45. TDTopezServer>>evaluateCommand:objIn: @19 line 22
46. TDTopezServer>>evaluateSTONCommand: @10 line 6
47. Executed Code
48. GsNMethod class>>_gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
Paul,

I think you need to do the following:

```Smalltalk
GsSecureSocket disableCertificateVerificationOnClient
```

The state is session-specific so it needs to be done once per login ...

**Comment by pdebruic** [comment]
So I'd have to add that to the gem startup scripts too then right?

And I don't know anything about client verification but is there a cert store (or something) I could load on to the servers to be able to use client verification?  It seems sane to want to use it.

**Comment by dalehenrich** [comment]
On 12/08/2016 10:07 AM, Paul DeBruicker wrote:
> So I'd have to add that to the gem startup scripts too then right?
right
>
> And I don't know anything about client verification but is there a 
> cert store (or something) I could load on to the servers to be able to 
> use client verification? It seems sane to want to use it.
>
Take a look at the class-side methods for GsSecureSocket ... there are 
quite a few examples there.

Dale

**Comment by pdebruic** [comment]
Thanks for the pointers.


On Ubuntu I ended up doing a:



GsSecureSocket useCACertificateFileForClients: '/etc/ssl/certs/ca-certificates.crt'. 



in the gem startup script and it seems to be working
